export const SITE = {
  title: "Heartopia Guide",
  description:
    "Free Heartopia strategy guides, redeem codes, walkthroughs, crafting recipes, and tips. Your complete companion for the cozy life-sim by XD Entertainment.",
  url: "https://heartopia.guide",
  defaultLanguage: "en",
  languages: ["en", "de", "it", "fr", "es", "ja", "ko", "id", "pl"] as const,
  languageLabels: {
    en: "English",
    de: "Deutsch",
    it: "Italiano",
    fr: "Français",
    es: "Español",
    ja: "日本語",
    ko: "한국어",
    id: "Bahasa Indonesia",
    pl: "Polski",
  },
};

export const NAV = [
  { label: "Beginner Guide", href: "/beginner-guide" },
  { label: "Codes", href: "/codes" },
  { label: "Walkthrough", href: "/walkthrough" },
  { label: "Characters", href: "/characters" },
  { label: "Resources", href: "/resources" },
  { label: "Hobbies", href: "/hobbies" },
  { label: "Crafting", href: "/crafting" },
  { label: "World Map", href: "/world-map" },
  { label: "Fish Guide", href: "/fish" },
  { label: "Bugs Guide", href: "/bugs" },
  { label: "Birds Guide", href: "/birds" },
  { label: "Recipes", href: "/recipes" },
];

export const MODULES = [
  {
    title: "Beginner Guide",
    href: "/beginner-guide",
    description: "Get started fast — character creation, DG levels, first-day priorities, and how to earn gold quickly.",
    priority: "P0",
  },
  {
    title: "Redeem Codes",
    href: "/codes",
    description: "All active Heartopia gift codes. Moonlight Crystals, Wishing Stars, and free materials — updated regularly.",
    priority: "P0",
  },
  {
    title: "Main Walkthrough",
    href: "/walkthrough",
    description: "Complete Astralis quest chain: Forest → Fishing Village → Flower Field → Onsen Mountain.",
    priority: "P0",
  },
  {
    title: "Characters & NPCs",
    href: "/characters",
    description: "Every NPC's location, role, unlock condition, and shop inventory — from Vanya to Doris.",
    priority: "P1",
  },
  {
    title: "Resources",
    href: "/resources",
    description: "Where to find every material: timber types, ores, foraged ingredients, and rare items like Flawless Fluorite.",
    priority: "P1",
  },
  {
    title: "Hobbies",
    href: "/hobbies",
    description: "Fishing, gardening, cooking, bug catching, birdwatching, and pet care — unlock guides and best strategies.",
    priority: "P2",
  },
  {
    title: "Crafting",
    href: "/crafting",
    description: "All crafting recipes with required materials — repair kits, furniture, bait, fertilizer, and special items.",
    priority: "P2",
  },
  {
    title: "Building & Decor",
    href: "/building",
    description: "Blueprints, co-building, custom furniture tricks, wallpaper hacks, and advanced decoration techniques.",
    priority: "P3",
  },
  {
    title: "Events",
    href: "/events",
    description: "Limited-time event guides: Winter Frost, Beaver Build Challenge, Wonder Egg Hunt, and seasonal activities.",
    priority: "P3",
  },
  {
    title: "Multiplayer",
    href: "/multiplayer",
    description: "Friends system, Coffee Umbrella social spots, cross-platform play, and co-building explained.",
    priority: "P3",
  },
  {
    title: "World Map",
    href: "/world-map",
    description: "Interactive Heartopia map with 300+ markers. Find all NPCs, fish, insects, birds, resources, shops, and bus stops.",
    priority: "P0",
  },
  {
    title: "Fish Guide",
    href: "/fish",
    description: "All 90 fish species with locations, levels, shadow sizes, weather conditions, time slots, and sell prices.",
    priority: "P1",
  },
  {
    title: "Bugs Guide",
    href: "/bugs",
    description: "All 69 insect species with spawn locations, levels, weather conditions, time slots, and sell prices.",
    priority: "P1",
  },
  {
    title: "Birds Guide",
    href: "/birds",
    description: "All 66 bird species with locations, levels, weather conditions, time slots, and sell prices.",
    priority: "P1",
  },
  {
    title: "Crops Guide",
    href: "/crops",
    description: "All 14 crops with gardening levels, growth times, seed prices, and sell prices by star rating.",
    priority: "P1",
  },
  {
    title: "Flowers Guide",
    href: "/flowers",
    description: "All 14 flower varieties with gardening levels, seed prices, and sell prices.",
    priority: "P2",
  },
  {
    title: "Forageables Guide",
    href: "/forageables",
    description: "All 27 wild forage items with sell prices, energy values, and locations.",
    priority: "P2",
  },
  {
    title: "Cats Guide",
    href: "/pets-cats",
    description: "All 18 cat breeds with favorite foods, sizes, and care tips.",
    priority: "P2",
  },
  {
    title: "Dogs Guide",
    href: "/pets-dogs",
    description: "All 34 dog breeds with favorite foods, sizes, and care tips.",
    priority: "P2",
  },
  {
    title: "Wild Animals Guide",
    href: "/wild-animals",
    description: "All 8 wild animal species with locations, favorite foods, and weather preferences.",
    priority: "P2",
  },
  {
    title: "Achievements Guide",
    href: "/achievements",
    description: "All 56 achievements with unlock conditions, tips, and reward titles.",
    priority: "P2",
  },
  {
    title: "Recipes Guide",
    href: "/recipes",
    description: "All 76 cooking recipes with ingredients, cooking levels, sell prices, and profit calculations.",
    priority: "P1",
  },
  {
    title: "Songs Guide",
    href: "/songs",
    description: "All 26 music sheets with song names and origins.",
    priority: "P3",
  },
];
